### ISSUE TITLE
"Building wheels for collected packages: pandas, numpy" require more than 15 minutes

### ISSUE THREAD

**Issue by OpenCode** [warp10/rocco#7]
Building wheels for `pandas` and `numpy`, require more than 15 minutes

```Collecting numpy>=1.17.3 (from pandas==1.3.4->-r /parts/project_addons/requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/c2/a8/a924a09492bdfee8c2ec3094d0a13f2799800b4fdc9c890738aeeb12c72e/numpy-1.21.5.zip (10.7MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
Building wheels for collected packages: pandas, numpy
  Running setup.py bdist_wheel for pandas: started
  Running setup.py bdist_wheel for pandas: still running...
  Running setup.py bdist_wheel for pandas: still running...
  Running setup.py bdist_wheel for pandas: still running...
  Running setup.py bdist_wheel for pandas: still running...
  Running setup.py bdist_wheel for pandas: still running...
```

**Comment by warp10** [comment]
This is not related to ROCCO in se. It is possibile to tell pip to download wheelfiles instead of building them from sources. Nevertheless, ROCCO is meant to be minimalist and to provide the bare minimum needed to start a vanilla Odoo instance that is reproducible on an on premises server or odoo.sh. Numpy and pandas are not needed on a minimal Odoo instance, hence I don't like the idea of fixing the issue on ROCCO. On the other hand, I expect the developer to change the Dockerfile and make it so that pip fetches the numpy/pandas/other_stuff wheelfiles instead of building them from source.
Closing this issue, but please reopen it if you disagree with me.
